"""assoc tables

Revision ID: 11014eda5437
Revises: 587ac9f3348b
Create Date: 2025-07-24 10:34:27.083433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11014eda5437'
down_revision = '587ac9f3348b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_role_to_organization_role',
    sa.Column('person_role_id', sa.UUID(), nullable=False),
    sa.Column('organization_role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_role_id'], ['party_role.id'], name=op.f('fk_person_role_to_organization_role_organization_role_id_party_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_role_id'], ['party_role.id'], name=op.f('fk_person_role_to_organization_role_person_role_id_party_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_role_id', 'organization_role_id', name=op.f('pk_person_role_to_organization_role'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_role_to_organization_role')
    # ### end Alembic commands ###
