"""add uuid_ossp

Revision ID: 6345b65750fc
Revises: 
Create Date: 2025-07-16 18:07:22.163358

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_extension import PGExtension
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '6345b65750fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_uuid_ossp = PGExtension(
        schema="public",
        signature="uuid-ossp"
    )
    op.create_entity(public_uuid_ossp)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_uuid_ossp = PGExtension(
        schema="public",
        signature="uuid-ossp"
    )
    op.drop_entity(public_uuid_ossp)

    # ### end Alembic commands ###
